
function __myhelp_aws_sre_tools__() {
    if [[ "$__verbose__" = TRUE ]]; then
        echo -e "     Profile Management:"
        echo -e "     ${YELLOW}aws_auth_update${NC}                 - Update AWS credentials"
        echo -e "     ${YELLOW}aws_profile_switch${NC}              - Switch AWS profiles"
        echo -e ""
        echo -e "     EKS:"
        echo -e "     ${YELLOW}cluster_connect${NC}                 - Connect to an EKS cluster"
        echo -e "     ${YELLOW}eks_cluster_info${NC}                - Get cluster information"
        echo -e "     ${YELLOW}eks_list_clusters${NC}               - List all EKS clusters"
        echo -e "     ${YELLOW}eks_node_groups${NC}                 - List node groups for a cluster"
        echo -e "     ${YELLOW}eks_update_kubeconfig${NC}           - Update kubeconfig for a cluster"
        echo -e "     ${YELLOW}list_kubernetes_objects${NC}         - List all Kubernetes objects in a specified namespace"
        echo -e "     ${YELLOW}list_node_group${NC}                 - List node groups for a cluster (Needs help)"
        echo -e ""
        echo -e "     EC2:"
        echo -e "     ${YELLOW}ec2_get_console_output${NC}          - Get console output"
        echo -e "     ${YELLOW}ec2_id_function${NC}                 - Get EC2 instance ID by name"
        echo -e "     ${YELLOW}ec2_list_instances${NC}              - List EC2 instances"
        echo -e "     ${YELLOW}ec2_ssm_connection${NC}              - Connect via SSM"
        echo -e "     ${YELLOW}ec2_start_instance${NC}              - Start an EC2 instance"
        echo -e "     ${YELLOW}ec2_stop_instance${NC}               - Stop an EC2 instance"
        echo -e "     ${YELLOW}ssm_parse_command_to_node_id${NC}    - Run command via SSM"
        echo -e ""
        echo -e "     S3:"
        echo -e "     ${YELLOW}s3_list_buckets${NC}                 - List S3 buckets"
        echo -e "     ${YELLOW}s3_sync_deploy${NC}                  - Deploy files to S3"
        echo -e "     ${YELLOW}s3_sync_test${NC}                    - Dry-run S3 sync"
        echo -e ""
        echo -e "     Lambda:"
        echo -e "     ${YELLOW}lambda_get_logs${NC}                 - Get Lambda logs"
        echo -e "     ${YELLOW}lambda_invoke_test${NC}              - Test invoke a Lambda"
        echo -e "     ${YELLOW}lambda_list_functions${NC}           - List Lambda functions"
        echo -e ""
        echo -e "     RDS:"
        echo -e "     ${YELLOW}rds_list_instances${NC}              - List RDS instances"
        echo -e ""
        echo -e "     Networking:"
        echo -e "     ${YELLOW}sg_list_security_groups${NC}         - List security groups"
        echo -e "     ${YELLOW}vpc_list_vpcs${NC}                   - List VPCs"
        echo -e ""
        echo -e "     Utilities:"
        echo -e "     ${YELLOW}aws_help${NC}                        - Show this help"
        echo -e "     ${YELLOW}aws_resource_count${NC}              - Count AWS resources"
    else
        echo -e "     ${YELLOW}aws_auth_update${NC}                 - Update AWS credentials"
        echo -e "     ${YELLOW}aws_help${NC}                        - Show AWS functions help"
        echo -e "     ${YELLOW}aws_profile_switch${NC}              - Switch AWS profiles"
        echo -e "     ${YELLOW}cluster_connect${NC}                 - Connect to an EKS cluster"
        echo -e "     ${YELLOW}ec2_id_function${NC}                 - Get EC2 instance ID by name"
        echo -e "     ${YELLOW}ec2_ssm_connection${NC}              - Connect via SSM"
        echo -e "     ${YELLOW}eks_cluster_info${NC}                - Get cluster information"
        echo -e "     ${YELLOW}eks_list_clusters${NC}               - List all EKS clusters"
        echo -e "     ${YELLOW}list_kubernetes_objects${NC}         - List all Kubernetes objects in a specified namespace"
        echo -e "     ${YELLOW}list_node_group${NC}                 - List node groups for a cluster (Needs help)"
        echo -e "     ${YELLOW}ssm_parse_command_to_node_id${NC}    - Run command via SSM"
        echo -e "     ${YELLOW}tshl${NC}                            - Teleport SSH login helper"
    fi
}